version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - 5001:80
    links:
      - mq
      - db
  worker:
    build: 
      context: .
      dockerfile: Worker.Dockerfile
    links:
      - mq
  mq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
    - 5672:5672
    - 15672:15672
  db:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password